// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdYTve3V7sZVK74UvvHt-YsJzfO0ZSjlk',
    appId: '1:835369419210:web:1dee99a13eb2dae7618f33',
    messagingSenderId: '835369419210',
    projectId: 'z1fsc-flutter-template',
    authDomain: 'z1fsc-flutter-template.firebaseapp.com',
    storageBucket: 'z1fsc-flutter-template.appspot.com',
    measurementId: 'G-QH4SQF5DK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeZFREN3Gky4jLpmcCW7yZMjcf15HiKVI',
    appId: '1:835369419210:android:a0f38dcdeb184c6d618f33',
    messagingSenderId: '835369419210',
    projectId: 'z1fsc-flutter-template',
    storageBucket: 'z1fsc-flutter-template.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZB-NyjKoJIMg9_BlvuUE5DI514YAmBM8',
    appId: '1:835369419210:ios:1a8a03ae0dc7ab4f618f33',
    messagingSenderId: '835369419210',
    projectId: 'z1fsc-flutter-template',
    storageBucket: 'z1fsc-flutter-template.appspot.com',
    iosClientId: '835369419210-n8gube39l6r5o3fht0bq08jq0p5dg7v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.z1fscFlutterTemplate',
  );
}
